site_name: Projeto BlackOps - Docs
site_description: Documentação tática do projeto BlackOps
site_author: Felip
site_url: https://blackops.local/
theme:
  name: material
  language: pt-BR
nav:
  - Início: index.md
  - Interface Streamlit: ui.md
  - Referência Técnica:
      - Módulo App: modules/app_interface.md
      - Módulo Blackops: modules/blackops_interface.md
  - Referência: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys; sys.path.append(".")