# -----------------------------
# config/settings.yaml
# -----------------------------
voice_control: true
camera_stream: true
relay_control: true
app_name: BlackOps
version: 1.0
author: Felipe
description: |
  Projeto de ciberseguranca BlackOps, integrado com modulos de IA, video,
  rede e controle fisico via relay. A interface e feita com Streamlit
  e suporta comandos de voz, OCR, seguranca em camadas e mais.