name: Build and Generate Provenance

on:
  push:
    branches: [main]
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build artifact
        run: |
          mkdir -p dist
          echo "Hello SLSA" > dist/hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: dist/hello.txt